

image: node:14.18.2

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass rsync

deploy_development:
  only:
    refs:
      - production
  stage: deploy
  environment: Development
  script:
    - yarn install
    - yarn build
    - ls  
    - cd build/
    - sshpass -V
    - export SSHPASS=$PRODUCTION_PASS
    - sshpass -e rsync -r --omit-dir-times -e "ssh -o StrictHostKeyChecking=no" . $PRODUCTION_USER_NAME@$PRODUCTION_IP:$PRODUCTION_FILE_LOCATION
