export enum Resources {
  CLIENTS = 'v1/admin-panel/clients',
  ARTISTSCREATE = 'v1/admin-panel/artist-profiles/create',
  ARTISTSUPDATE = 'v1/admin-panel/artist-profiles/update',
  ARTISTSDELETE = 'v1/admin-panel/artist-profiles/delete',
  ORDERS = 'v1/admin-panel/orders',
  SECRETSLIST = 'v1/admin-panel/secrets/find',
  SECRETSCREATE = 'v1/admin-panel/secrets',
  SECRETSDELETE = 'v1/admin-panel/secrets',
  PROMOCODELIST = "v1/admin-panel/promocode/find",
  PROMOCODECREATE = "v1/admin-panel/promocode",
  PROMOCODEDELETE = "v1/admin-panel/promocode",
  SERVICESCREATE = "v1/admin-panel/artist-profiles/set-service",
  UPLOADIMAGE = "v1/admin-panel/artist-profiles/bucket/image/get-presigned-put-url",
}
